language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "travistest"
    token:
      secure: "b6099edd5754ea1d9322d3649e5511d74528cba6"
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
